### ISSUE TITLE
Spring batch and Transactional

### ISSUE THREAD

**Issue by winters1224** [winters1224/blogs#5]
A task of spring batch was writen as following in my team:

``` java
public class XxxTask{
    private Job xxJob;
    private JobLauncher laucher;
    public void execute(){
        // get parameters
        Map<String, Object> param =...
        // execute the job
        try{
                laucher.execute( xxJob, param);
        }catch(){
                ......
         }
    }
}
```

If a database transaction was created when "get parameters", no matter it's reading from or writing to the database, then an exception will be thrown when "execute job". The exception is:

``` java
java.lang.IllegalStateException: Existing transaction detected in JobRepository. Please fix this and try again (e.g. remove @Transactional annotations from client).
```

The internet said, the field named "validateTransactionState" of class "AbstractJobRepositoryFactoryBean" was set to TRUE, so the spring batch checked that whether a transaction was existed in the current thread. Then that exception happend as there is one transactoin already. The interrelated code is:

``` java
private void initializeProxy() throws Exception {
    if (proxyFactory == null) {
        proxyFactory = new ProxyFactory();
        TransactionInterceptor advice = new TransactionInterceptor(transactionManager,
                PropertiesConverter.stringToProperties("create*=PROPAGATION_REQUIRES_NEW,"
                        + isolationLevelForCreate + "\ngetLastJobExecution*=PROPAGATION_REQUIRES_NEW,"
                        + isolationLevelForCreate + "\n*=PROPAGATION_REQUIRED"));
        if (validateTransactionState) {
            DefaultPointcutAdvisor advisor = new DefaultPointcutAdvisor(new MethodInterceptor() {
                @Override
                public Object invoke(MethodInvocation invocation) throws Throwable {
                    if (TransactionSynchronizationManager.isActualTransactionActive()) {
                        throw new IllegalStateException(
                                "Existing transaction detected in JobRepository. "
                                        + "Please fix this and try again (e.g. remove @Transactional annotations from client).");
                    }
                    return invocation.proceed();
                }
            });
            NameMatchMethodPointcut pointcut = new NameMatchMethodPointcut();
            pointcut.addMethodName("create*");
            advisor.setPointcut(pointcut);
            proxyFactory.addAdvisor(advisor);
        }
        proxyFactory.addAdvice(advice);
        proxyFactory.setProxyTargetClass(false);
        proxyFactory.addInterface(JobRepository.class);
        proxyFactory.setTarget(getTarget());
    }
}
```

So I configurate it by xml, like this:

``` xml
<bean id="jobRepository"
    class="org.springframework.batch.core.repository.support.JobRepositoryFactoryBean">
    <property name="transactionManager" ref="transactionManager" />
    <property name="dataSource" ref="dataSource" />
    <property name="validateTransactionState" value="false" />
</bean>
```

Well, one problem was resolved, and another one emerged:

``` java
十二月 28, 2015 6:40:05 下午 org.springframework.batch.core.job.AbstractJob execute

严重: Encountered fatal error executing job

org.springframework.dao.EmptyResultDataAccessException: Incorrect result size: expected 1, actual 0
    at org.springframework.dao.support.DataAccessUtils.requiredSingleResult(DataAccessUtils.java:71)
    at org.springframework.jdbc.core.JdbcTemplate.queryForObject(JdbcTemplate.java:791)
    at org.springframework.jdbc.core.JdbcTemplate.queryForObject(JdbcTemplate.java:814)
    at org.springframework.batch.core.repository.dao.JdbcJobExecutionDao.synchronizeStatus(JdbcJobExecutionDao.java:301)
    at org.springframework.batch.core.repository.support.SimpleJobRepository.update(SimpleJobRepository.java:161)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:302)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
    at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
    at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
    at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
    at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
    at com.sun.proxy.$Proxy97.update(Unknown Source)
    at org.springframework.batch.core.job.AbstractJob.updateStatus(AbstractJob.java:416)
    at org.springframework.batch.core.job.AbstractJob.execute(AbstractJob.java:299)
    at org.springframework.batch.core.launch.support.SimpleJobLauncher$1.run(SimpleJobLauncher.java:135)
    at org.springframework.core.task.SyncTaskExecutor.execute(SyncTaskExecutor.java:50)
    at org.springframework.batch.core.launch.support.SimpleJobLauncher.run(SimpleJobLauncher.java:128)
    at cn.youcredit.thread.common.task.TaskUtils.launchJob(TaskUtils.java:99)
    at cn.youcredit.thread.task.auth.AuthSyncTask.syncGroupInfos(AuthSyncTask.java:89)
    at cn.youcredit.thread.task.auth.AuthSyncTask$$FastClassBySpringCGLIB$$b0cb6150.invoke(<generated>)
    at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
    at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:717)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
    at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
    at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
    at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
    at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:653)
    at cn.youcredit.thread.task.auth.AuthSyncTask$$EnhancerBySpringCGLIB$$91744a87.syncGroupInfos(<generated>)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
    at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
    at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

I'll try to resolve the second problem. And then, record the solution here.

**Comment by kalyankiranb** [comment]
Have you resolved this issue? I am facing the same problem.
